"""Přidal tabulku Subjekty

Revision ID: 6531e1cfd8a7
Revises: 
Create Date: 2020-09-22 07:36:44.632075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6531e1cfd8a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjekty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cislo_licence', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('version_status', sa.String(length=64), nullable=True),
    sa.Column('subjekt_ic', sa.String(length=9), nullable=True),
    sa.Column('subjekt_nazev', sa.String(length=128), nullable=True),
    sa.Column('subjekt_cislo_dom', sa.String(length=10), nullable=True),
    sa.Column('subjekt_cislo_or', sa.String(length=10), nullable=True),
    sa.Column('subjekt_ulice_nazev', sa.String(length=64), nullable=True),
    sa.Column('subjekt_obec_cast', sa.String(length=64), nullable=True),
    sa.Column('subjekt_obec_nazev', sa.String(length=64), nullable=True),
    sa.Column('subjekt_psc', sa.String(length=6), nullable=True),
    sa.Column('subjekt_okres', sa.String(length=64), nullable=True),
    sa.Column('subjekt_kraj', sa.String(length=64), nullable=True),
    sa.Column('subjekt_zeme', sa.String(length=64), nullable=True),
    sa.Column('subjekt_den_opravneni', sa.Date(), nullable=True),
    sa.Column('subjekt_den_zahajeni', sa.Date(), nullable=True),
    sa.Column('subjekt_den_zaniku', sa.Date(), nullable=True),
    sa.Column('subjekt_den_nabyti_pravni_moci', sa.Date(), nullable=True),
    sa.Column('predmet', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjekty_cislo_licence'), 'subjekty', ['cislo_licence'], unique=False)
    op.create_index(op.f('ix_subjekty_subjekt_ic'), 'subjekty', ['subjekt_ic'], unique=False)
    op.create_index(op.f('ix_subjekty_version'), 'subjekty', ['version'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subjekty_version'), table_name='subjekty')
    op.drop_index(op.f('ix_subjekty_subjekt_ic'), table_name='subjekty')
    op.drop_index(op.f('ix_subjekty_cislo_licence'), table_name='subjekty')
    op.drop_table('subjekty')
    # ### end Alembic commands ###
