"""Added columns in Subjekt table

Revision ID: 7b9ae37ea056
Revises: 6531e1cfd8a7
Create Date: 2020-09-23 06:48:37.637197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b9ae37ea056'
down_revision = '6531e1cfd8a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjekty', sa.Column('celkovy_el', sa.Float(), nullable=True))
    op.add_column('subjekty', sa.Column('celkovy_tep', sa.Float(), nullable=True))
    op.add_column('subjekty', sa.Column('horkovodni_el', sa.Float(), nullable=True))
    op.add_column('subjekty', sa.Column('horkovodni_tep', sa.Float(), nullable=True))
    op.add_column('subjekty', sa.Column('jaderny_el', sa.Float(), nullable=True))
    op.add_column('subjekty', sa.Column('jaderny_tep', sa.Float(), nullable=True))
    op.add_column('subjekty', sa.Column('kogenerace_el', sa.Float(), nullable=True))
    op.add_column('subjekty', sa.Column('kogenerace_tep', sa.Float(), nullable=True))
    op.add_column('subjekty', sa.Column('kvet_el', sa.Float(), nullable=True))
    op.add_column('subjekty', sa.Column('kvet_tep', sa.Float(), nullable=True))
    op.add_column('subjekty', sa.Column('odpovedny_zastupce', sa.String(length=64), nullable=True))
    op.add_column('subjekty', sa.Column('ostatni_el', sa.Float(), nullable=True))
    op.add_column('subjekty', sa.Column('ostatni_tep', sa.Float(), nullable=True))
    op.add_column('subjekty', sa.Column('parni_el', sa.Float(), nullable=True))
    op.add_column('subjekty', sa.Column('parni_tep', sa.Float(), nullable=True))
    op.add_column('subjekty', sa.Column('paroplynova_el', sa.Float(), nullable=True))
    op.add_column('subjekty', sa.Column('paroplynova_tep', sa.Float(), nullable=True))
    op.add_column('subjekty', sa.Column('plynovy_el', sa.Float(), nullable=True))
    op.add_column('subjekty', sa.Column('plynovy_tep', sa.Float(), nullable=True))
    op.add_column('subjekty', sa.Column('pocet_zdroju', sa.Integer(), nullable=True))
    op.add_column('subjekty', sa.Column('precerpavaci_el', sa.Float(), nullable=True))
    op.add_column('subjekty', sa.Column('precerpavaci_tep', sa.Float(), nullable=True))
    op.add_column('subjekty', sa.Column('slunecni_el', sa.Float(), nullable=True))
    op.add_column('subjekty', sa.Column('slunecni_tep', sa.Float(), nullable=True))
    op.add_column('subjekty', sa.Column('teplovodni_el', sa.Float(), nullable=True))
    op.add_column('subjekty', sa.Column('teplovodni_tep', sa.Float(), nullable=True))
    op.add_column('subjekty', sa.Column('vetrny_el', sa.Float(), nullable=True))
    op.add_column('subjekty', sa.Column('vetrny_tep', sa.Float(), nullable=True))
    op.add_column('subjekty', sa.Column('vodni_el', sa.Float(), nullable=True))
    op.add_column('subjekty', sa.Column('vodni_tep', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subjekty', 'vodni_tep')
    op.drop_column('subjekty', 'vodni_el')
    op.drop_column('subjekty', 'vetrny_tep')
    op.drop_column('subjekty', 'vetrny_el')
    op.drop_column('subjekty', 'teplovodni_tep')
    op.drop_column('subjekty', 'teplovodni_el')
    op.drop_column('subjekty', 'slunecni_tep')
    op.drop_column('subjekty', 'slunecni_el')
    op.drop_column('subjekty', 'precerpavaci_tep')
    op.drop_column('subjekty', 'precerpavaci_el')
    op.drop_column('subjekty', 'pocet_zdroju')
    op.drop_column('subjekty', 'plynovy_tep')
    op.drop_column('subjekty', 'plynovy_el')
    op.drop_column('subjekty', 'paroplynova_tep')
    op.drop_column('subjekty', 'paroplynova_el')
    op.drop_column('subjekty', 'parni_tep')
    op.drop_column('subjekty', 'parni_el')
    op.drop_column('subjekty', 'ostatni_tep')
    op.drop_column('subjekty', 'ostatni_el')
    op.drop_column('subjekty', 'odpovedny_zastupce')
    op.drop_column('subjekty', 'kvet_tep')
    op.drop_column('subjekty', 'kvet_el')
    op.drop_column('subjekty', 'kogenerace_tep')
    op.drop_column('subjekty', 'kogenerace_el')
    op.drop_column('subjekty', 'jaderny_tep')
    op.drop_column('subjekty', 'jaderny_el')
    op.drop_column('subjekty', 'horkovodni_tep')
    op.drop_column('subjekty', 'horkovodni_el')
    op.drop_column('subjekty', 'celkovy_tep')
    op.drop_column('subjekty', 'celkovy_el')
    # ### end Alembic commands ###
