"""Tables subjekt and provozovna

Revision ID: 8e906b0ea6a7
Revises: 
Create Date: 2020-09-23 11:06:07.689981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e906b0ea6a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjekty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cislo_licence', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('version_status', sa.String(length=64), nullable=True),
    sa.Column('subjekt_ic', sa.String(length=9), nullable=True),
    sa.Column('subjekt_nazev', sa.String(length=128), nullable=True),
    sa.Column('subjekt_cislo_dom', sa.String(length=10), nullable=True),
    sa.Column('subjekt_cislo_or', sa.String(length=10), nullable=True),
    sa.Column('subjekt_ulice_nazev', sa.String(length=64), nullable=True),
    sa.Column('subjekt_obec_cast', sa.String(length=64), nullable=True),
    sa.Column('subjekt_obec_nazev', sa.String(length=64), nullable=True),
    sa.Column('subjekt_psc', sa.String(length=6), nullable=True),
    sa.Column('subjekt_okres', sa.String(length=64), nullable=True),
    sa.Column('subjekt_kraj', sa.String(length=64), nullable=True),
    sa.Column('subjekt_zeme', sa.String(length=64), nullable=True),
    sa.Column('subjekt_den_opravneni', sa.Date(), nullable=True),
    sa.Column('subjekt_den_zahajeni', sa.Date(), nullable=True),
    sa.Column('subjekt_den_zaniku', sa.Date(), nullable=True),
    sa.Column('subjekt_den_nabyti_pravni_moci', sa.Date(), nullable=True),
    sa.Column('predmet', sa.String(length=64), nullable=True),
    sa.Column('odpovedny_zastupce', sa.String(length=64), nullable=True),
    sa.Column('verze_licence', sa.Integer(), nullable=True),
    sa.Column('pocet_zdroju', sa.Integer(), nullable=True),
    sa.Column('celkovy_el', sa.Float(), nullable=True),
    sa.Column('celkovy_tep', sa.Float(), nullable=True),
    sa.Column('horkovodni_el', sa.Float(), nullable=True),
    sa.Column('horkovodni_tep', sa.Float(), nullable=True),
    sa.Column('teplovodni_el', sa.Float(), nullable=True),
    sa.Column('teplovodni_tep', sa.Float(), nullable=True),
    sa.Column('parni_el', sa.Float(), nullable=True),
    sa.Column('parni_tep', sa.Float(), nullable=True),
    sa.Column('kvet_el', sa.Float(), nullable=True),
    sa.Column('kvet_tep', sa.Float(), nullable=True),
    sa.Column('kogenerace_el', sa.Float(), nullable=True),
    sa.Column('kogenerace_tep', sa.Float(), nullable=True),
    sa.Column('plynovy_el', sa.Float(), nullable=True),
    sa.Column('plynovy_tep', sa.Float(), nullable=True),
    sa.Column('jaderny_el', sa.Float(), nullable=True),
    sa.Column('jaderny_tep', sa.Float(), nullable=True),
    sa.Column('precerpavaci_el', sa.Float(), nullable=True),
    sa.Column('precerpavaci_tep', sa.Float(), nullable=True),
    sa.Column('paroplynova_el', sa.Float(), nullable=True),
    sa.Column('paroplynova_tep', sa.Float(), nullable=True),
    sa.Column('slunecni_el', sa.Float(), nullable=True),
    sa.Column('slunecni_tep', sa.Float(), nullable=True),
    sa.Column('vetrny_el', sa.Float(), nullable=True),
    sa.Column('vetrny_tep', sa.Float(), nullable=True),
    sa.Column('vodni_el', sa.Float(), nullable=True),
    sa.Column('vodni_tep', sa.Float(), nullable=True),
    sa.Column('ostatni_el', sa.Float(), nullable=True),
    sa.Column('ostatni_tep', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subjekty_cislo_licence'), 'subjekty', ['cislo_licence'], unique=False)
    op.create_index(op.f('ix_subjekty_subjekt_ic'), 'subjekty', ['subjekt_ic'], unique=False)
    op.create_index(op.f('ix_subjekty_version'), 'subjekty', ['version'], unique=False)
    op.create_table('provozovny',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ev_cislo', sa.Integer(), nullable=True),
    sa.Column('nazev', sa.String(length=128), nullable=True),
    sa.Column('adresa', sa.String(length=128), nullable=True),
    sa.Column('psc', sa.String(length=6), nullable=True),
    sa.Column('obec', sa.String(length=64), nullable=True),
    sa.Column('ulice', sa.String(length=64), nullable=True),
    sa.Column('cp', sa.String(length=64), nullable=True),
    sa.Column('okres', sa.String(length=64), nullable=True),
    sa.Column('kraj', sa.String(length=64), nullable=True),
    sa.Column('katastralni_uzemi', sa.String(length=64), nullable=True),
    sa.Column('kod_katastru', sa.Integer(), nullable=True),
    sa.Column('vymezeni', sa.String(length=64), nullable=True),
    sa.Column('pocet_zdroju', sa.Integer(), nullable=True),
    sa.Column('celkovy_el', sa.Float(), nullable=True),
    sa.Column('celkovy_tep', sa.Float(), nullable=True),
    sa.Column('horkovodni_el', sa.Float(), nullable=True),
    sa.Column('horkovodni_tep', sa.Float(), nullable=True),
    sa.Column('teplovodni_el', sa.Float(), nullable=True),
    sa.Column('teplovodni_tep', sa.Float(), nullable=True),
    sa.Column('parni_el', sa.Float(), nullable=True),
    sa.Column('parni_tep', sa.Float(), nullable=True),
    sa.Column('kvet_el', sa.Float(), nullable=True),
    sa.Column('kvet_tep', sa.Float(), nullable=True),
    sa.Column('kogenerace_el', sa.Float(), nullable=True),
    sa.Column('kogenerace_tep', sa.Float(), nullable=True),
    sa.Column('plynovy_el', sa.Float(), nullable=True),
    sa.Column('plynovy_tep', sa.Float(), nullable=True),
    sa.Column('jaderny_el', sa.Float(), nullable=True),
    sa.Column('jaderny_tep', sa.Float(), nullable=True),
    sa.Column('precerpavaci_el', sa.Float(), nullable=True),
    sa.Column('precerpavaci_tep', sa.Float(), nullable=True),
    sa.Column('paroplynova_el', sa.Float(), nullable=True),
    sa.Column('paroplynova_tep', sa.Float(), nullable=True),
    sa.Column('slunecni_el', sa.Float(), nullable=True),
    sa.Column('slunecni_tep', sa.Float(), nullable=True),
    sa.Column('vetrny_el', sa.Float(), nullable=True),
    sa.Column('vetrny_tep', sa.Float(), nullable=True),
    sa.Column('vodni_el', sa.Float(), nullable=True),
    sa.Column('vodni_tep', sa.Float(), nullable=True),
    sa.Column('ostatni_el', sa.Float(), nullable=True),
    sa.Column('ostatni_tep', sa.Float(), nullable=True),
    sa.Column('vodni_tok', sa.String(length=64), nullable=True),
    sa.Column('ricni_km', sa.Float(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.Column('druh', sa.String(length=64), nullable=True),
    sa.Column('subjekt_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subjekt_id'], ['subjekty.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_provozovny_ev_cislo'), 'provozovny', ['ev_cislo'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_provozovny_ev_cislo'), table_name='provozovny')
    op.drop_table('provozovny')
    op.drop_index(op.f('ix_subjekty_version'), table_name='subjekty')
    op.drop_index(op.f('ix_subjekty_subjekt_ic'), table_name='subjekty')
    op.drop_index(op.f('ix_subjekty_cislo_licence'), table_name='subjekty')
    op.drop_table('subjekty')
    # ### end Alembic commands ###
